name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug.
      placeholder: The feature x...
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug
      placeholder: |
        - Open the application...
        - Click here...
    validations:
      required: true
  - type: textarea
    id: expected_result
    attributes:
      label: Expected Result
      description: Describe what you expect to happen
      placeholder: The feature must...
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Include any other relevant information here.
